// File generated by Antigravity to bypass PATH issues
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATiq3Hwkrr1Rlj5pO6m1ogqgAYuT_-Sqw',
    appId: '1:22658116361:web:10bbc3a25a21e3137a81d8',
    messagingSenderId: '22658116361',
    projectId: 'smart-mess-college',
    authDomain: 'smart-mess-college.firebaseapp.com',
    storageBucket: 'smart-mess-college.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATiq3Hwkrr1Rlj5pO6m1ogqgAYuT_-Sqw',
    appId: '1:22658116361:web:10bbc3a25a21e3137a81d8', // Mapped from web to bypass CLI issues
    messagingSenderId: '22658116361',
    projectId: 'smart-mess-college',
    storageBucket: 'smart-mess-college.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATiq3Hwkrr1Rlj5pO6m1ogqgAYuT_-Sqw',
    appId: '1:22658116361:web:10bbc3a25a21e3137a81d8',
    messagingSenderId: '22658116361',
    projectId: 'smart-mess-college',
    storageBucket: 'smart-mess-college.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATiq3Hwkrr1Rlj5pO6m1ogqgAYuT_-Sqw',
    appId: '1:22658116361:web:10bbc3a25a21e3137a81d8',
    messagingSenderId: '22658116361',
    projectId: 'smart-mess-college',
    storageBucket: 'smart-mess-college.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATiq3Hwkrr1Rlj5pO6m1ogqgAYuT_-Sqw',
    appId: '1:22658116361:web:10bbc3a25a21e3137a81d8',
    messagingSenderId: '22658116361',
    projectId: 'smart-mess-college',
    storageBucket: 'smart-mess-college.firebasestorage.app',
  );
}
